const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.destroy,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X
	];
};
self.C3_JsPropNameTable = [
	{fundofloresta: 0},
	{Sólido: 0},
	{chao1: 0},
	{chao2: 0},
	{chao3: 0},
	{terreno1: 0},
	{terreno2: 0},
	{terreno3: 0},
	{chaovoando1: 0},
	{chaovoando2: 0},
	{chaovoando3: 0},
	{platVoando1: 0},
	{platVoando2: 0},
	{platVoando3: 0},
	{ativado: 0},
	{Esmaecer: 0},
	{chaoestavel: 0},
	{Fixar: 0},
	{animaçao: 0},
	{morrendo: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{DestruirExternamente: 0},
	{jogador: 0},
	{banco1: 0},
	{banco2: 0},
	{lixo: 0},
	{Áudio: 0},
	{dinheiro: 0},
	{fonte: 0},
	{grama1: 0},
	{grama2: 0},
	{arvore1: 0},
	{arvore2: 0},
	{Âncora: 0},
	{Pontuaçao: 0},
	{arbusto1: 0},
	{arbusto2: 0},
	{arbusto3: 0},
	{arbusto4: 0},
	{arbusto5: 0},
	{esmeralda: 0},
	{nomeDaFase: 0},
	{açao: 0},
	{vida: 0},
	{inimigo1: 0},
	{marcador: 0},
	{limitelayout: 0},
	{telainicio: 0},
	{Botão: 0},
	{Mouse: 0},
	{versão: 0},
	{Teclado: 0},
	{telafinal: 0},
	{gameover: 0},
	{inimigo2: 0},
	{Projétil: 0},
	{bola: 0},
	{tecla1: 0},
	{tecla2: 0},
	{tecla3: 0},
	{tutorial: 0},
	{pontos: 0}
];

self.InstanceType = {
	fundofloresta: class extends self.ISpriteInstance {},
	chao1: class extends self.ISpriteInstance {},
	chao2: class extends self.ISpriteInstance {},
	chao3: class extends self.ISpriteInstance {},
	terreno1: class extends self.ISpriteInstance {},
	terreno2: class extends self.ISpriteInstance {},
	terreno3: class extends self.ISpriteInstance {},
	chaovoando1: class extends self.ISpriteInstance {},
	chaovoando2: class extends self.ISpriteInstance {},
	chaovoando3: class extends self.ISpriteInstance {},
	platVoando1: class extends self.ISpriteInstance {},
	platVoando2: class extends self.ISpriteInstance {},
	platVoando3: class extends self.ISpriteInstance {},
	chaoestavel: class extends self.ISpriteInstance {},
	animaçao: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	banco1: class extends self.ISpriteInstance {},
	banco2: class extends self.ISpriteInstance {},
	lixo: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	dinheiro: class extends self.ISpriteInstance {},
	fonte: class extends self.ISpriteInstance {},
	grama1: class extends self.ISpriteInstance {},
	grama2: class extends self.ISpriteInstance {},
	arvore1: class extends self.ISpriteInstance {},
	arvore2: class extends self.ISpriteInstance {},
	Pontuaçao: class extends self.ITextInstance {},
	arbusto1: class extends self.ISpriteInstance {},
	arbusto2: class extends self.ISpriteInstance {},
	arbusto3: class extends self.ISpriteInstance {},
	arbusto4: class extends self.ISpriteInstance {},
	arbusto5: class extends self.ISpriteInstance {},
	esmeralda: class extends self.ISpriteInstance {},
	nomeDaFase: class extends self.ITextInstance {},
	inimigo1: class extends self.ISpriteInstance {},
	marcador: class extends self.ISpriteInstance {},
	limitelayout: class extends self.ISpriteInstance {},
	telainicio: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Mouse: class extends self.IInstance {},
	versão: class extends self.ITextInstance {},
	Teclado: class extends self.IInstance {},
	telafinal: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteInstance {},
	inimigo2: class extends self.ISpriteInstance {},
	bola: class extends self.ISpriteInstance {},
	tecla1: class extends self.ISpriteInstance {},
	tecla2: class extends self.ISpriteInstance {},
	tecla3: class extends self.ISpriteInstance {},
	tutorial: class extends self.ITextInstance {}
}